[load_balancer]
HAProxyLB_VM ansible_host=192.168.222.205

[web_servers]
WebServOne_VM ansible_host=192.168.222.220
WebServTwo_VM ansible_host=192.168.222.225

[all:vars]
ansible_user=UserOne
ansible_become=yes
ansible_become_method=sudo
ansible_become_user=root
ansible_ssh_private_key_file=/home/amw/Office/DevOps/linux-high-availability-Prjct_03/Lab_VMs/VMs_Keys/Repo3_VMs_key_ed25519
